version: '2.1'

services:
  funcionario-microservice:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    expose:
      - "3000"
    environment:
      - NODE_ENV=test
      - AUTH_API_HOST=localhost
      - AUTH_API_PORT=3000
      - DB_URL=mongodb://172.17.0.1/test
    volumes:
      - ./funcionario-microservice:/home/node/app
    command: "yarn start"

  atendimento-microservice:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    expose:
      - "3000"
    environment:
      - NODE_ENV=test
      - AUTH_API_HOST=funcionario-microservice
      - AUTH_API_PORT=3000
      - DB_URL=mongodb://172.17.0.1/test
    links:
      - funcionario-microservice
    volumes:
      - ./atendimento-microservice:/home/node/app
      - /images:/usr/src/app/public/imagens
    command: "yarn start"

  cliente-microservice:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    expose:
      - "3000"
    environment:
      - NODE_ENV=test
      - AUTH_API_HOST=funcionario-microservice
      - AUTH_API_PORT=3000
      - DB_URL=mongodb://172.17.0.1/test
    links:
      - funcionario-microservice
    volumes:
      - ./cliente-microservice:/home/node/app
    command: "yarn start"

  log-microservice:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    expose:
      - "3000"
    environment:
      - NODE_ENV=test
      - AUTH_API_HOST=funcionario-microservice
      - AUTH_API_PORT=3000
      - DB_URL=mongodb://172.17.0.1/test
    links:
      - funcionario-microservice
    volumes:
      - ./log-microservice:/home/node/app
    command: "yarn live"

  nginx:
    build: ./nginx
    links:
      - atendimento-microservice
      - cliente-microservice
      - funcionario-microservice
      - log-microservice
    ports:
      - "3000:80"
